# Site/SEO settings
email: christina.kasperczyk@web.de
permalink: /:year/:month/:day/:title/
google_analytics: 

title: A Short Cut To Mushrooms
description: A Short Cut To Mushrooms - Mein Trekking-, Wander- und Kletter-Blog
url: ""
baseurl: "/a-short-cut-to-mushrooms"
twitter_username: 
default_img: 

# Profile settings
name: Christina Kasperczyk
profile_img: /a-short-cut-to-mushrooms/assets/img/profile.JPG
profile: "Seit ich mit ungefähr 15 Jahren den Herrn der Ringe verschlungen hatte und natürlich auch von den Filmen
begeistern war, war es mein Traum in Neuseeland Wandern zu gehen. Im Jahr 2007 sollte der Traum dann Wirklichkeit
werden. Nach dem Abi war ein halbes Jahr Neuseeland eingeplant. Meinen Reisegefährten Frieder hatte ich im Internet
kennengelernt. Ihn trieb das gleiche Fernweh an wie mich. Doch dann kam doch alles anders. Anfang 2007 kam ich mit
meinem ersten Freund Matthias zusammen und Neuseeland verschob sich auf der Dringlichkeitskala in meinem Kopf irgendwo
ganz nach hinten. Der Neuseeland-Trip wurde abgesagt, bzw. Frieder flog alleine dort hin. Bei mir folgte das Studium
und außer ein paar Urlauben in Holland, Sachsen und Österreich (in denen zwar gewandert wurde, aber immer nur in
Tagesetappen) geschah in dieser Zeit nicht viel in Sachen Trekking. Irgendwann wurde mir dann klar, dass es ja nicht
direkt Neuseeland sein muss. Europa bietet ja auch schon unendlich viele tolle Wanderlandschaften, die sich ebenso gut
zum Trekking anbieten, noch besser sogar, denn die Anreise dorthin ist ja wesentlich günstiger als der ewig lange Flug
auf die andere Seite der Welt. Ende 2010 kam also der Entschluss, endlich auf Trekking-Tour zu gehen. Ein Mitreisender
war schnell gefunden. Meine Mutter hatte ebenfalls die Abenteuer-Lust gepackt. So flogen wir dann im März 2011 nach
Irland und wanderten den Ker-ry Way. Eine Erfahrung, die mich wohl für den Rest meines Leben geprägt hat. Seit dem bin
ich so viel wie möglich mit dem Rucksack unterwegs und erkunde die Welt. Die Welt ist wohl ein bisschen viel gesagt,
denn bisher war ich nur in Europa unter-wegs, aber seit ich in Irland war, zieht es mich auch nicht mehr so auf die
andere Seite der Erde. In diesem Blog möchte ich nun meine Erfahrungen mit Gleichgesinnten teilen. A Short Cut To
Mushrooms - Querfeldein zu den Pilzen! So bin ich am liebsten unterwegs, ohne Wege durch die Natur oder auf verlassenen
Pfaden durchs Dickicht."
social:
  github: https://github.com/Kasperczyk/a-short-cut-to-mushrooms
  facebook: https://www.facebook.com/profile.php?id=100001162374016
  instagram: https://www.instagram.com/pinkgorillasbouldering/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
